name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: |
          thesis-example.tex
